### ISSUE TITLE
实现跟跟论文图不一致

### ISSUE THREAD

**Issue by iFe1er** [kaiwenzha/Rank-N-Contrast#4]
论文图的年龄回归问题，是把anchor的neighbor作为positive pair。但是在实现的时候，用的是anchor的random transform当作positive pair。。因此，最终的效果提升怎么排除是来自于图像数据增强呢？

**Comment by kaiwenzha** [comment]
Hi, thank you for your interest in our work.

To clarify, Fig. 2 is meant to illustrate our core idea, and for simplicity, we do not show the two augmented views for each sample. However, in the text descriptions of our approach (see Sec. 3 in our paper), we have clearly stated that our approach operates on a two-view batch, which is consistent with our implementation. 

Regarding your concern about the effect of data augmentation, we've already discussed it in Sec. 5.4 and conducted detailed ablation studies in Appendix G.3, in which we have shown that our method consistently outperforms the baseline with or without data augmentation. This confirms that the performance gain of RnC stems from our proposed loss rather than the data augmentation.
